server:
  port: 80
zuul:
  routes:
    channels:
      path: /channels-management/**
      serviceId: channels-service

spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url.default: http://localhost:8761/eureka
